package com.guet.qiusuo.fruittravel.model;

import javax.annotation.Generated;

/**
 * Database Table Remarks:
 * 水果商品子项表
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbl_child_fruit
 */
public class ChildFruit {
    /**
     * Database Column Remarks:
     * uuid
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.216+08:00",
            comments = "Source field: tbl_child_fruit.id")
    private String id;

    /**
     * Database Column Remarks:
     * 水果商品id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.217+08:00",
            comments = "Source field: tbl_child_fruit.fruit_id")
    private String fruitId;

    /**
     * Database Column Remarks:
     * 水果名称
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.217+08:00",
            comments = "Source field: tbl_child_fruit.fruit_name")
    private String fruitName;

    /**
     * Database Column Remarks:
     * 水果价钱(一个数字)
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.217+08:00",
            comments = "Source field: tbl_child_fruit.fruit_price")
    private Integer fruitPrice;

    /**
     * Database Column Remarks:
     * 库存数量
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.stock")
    private Integer stock;

    /**
     * Database Column Remarks:
     * 图片存储路径
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.image_url")
    private String imageUrl;

    /**
     * Database Column Remarks:
     * 状态,0: 无效 1: 有效
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.status")
    private Short status;

    /**
     * Database Column Remarks:
     * 创建时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.create_time")
    private Long createTime;

    /**
     * Database Column Remarks:
     * 最后更新时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.update_time")
    private Long updateTime;

    /**
     * Database Column Remarks:
     * 增加此条数据的用户id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.219+08:00",
            comments = "Source field: tbl_child_fruit.create_user_id")
    private String createUserId;

    /**
     * Database Column Remarks:
     * 最后更新此条数据的用户id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.219+08:00",
            comments = "Source field: tbl_child_fruit.update_user_id")
    private String updateUserId;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.216+08:00",
            comments = "Source field: tbl_child_fruit.id")
    public String getId() {
        return id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.217+08:00",
            comments = "Source field: tbl_child_fruit.id")
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.217+08:00",
            comments = "Source field: tbl_child_fruit.fruit_id")
    public String getFruitId() {
        return fruitId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.217+08:00",
            comments = "Source field: tbl_child_fruit.fruit_id")
    public void setFruitId(String fruitId) {
        this.fruitId = fruitId == null ? null : fruitId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.217+08:00",
            comments = "Source field: tbl_child_fruit.fruit_name")
    public String getFruitName() {
        return fruitName;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.217+08:00",
            comments = "Source field: tbl_child_fruit.fruit_name")
    public void setFruitName(String fruitName) {
        this.fruitName = fruitName == null ? null : fruitName.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.217+08:00",
            comments = "Source field: tbl_child_fruit.fruit_price")
    public Integer getFruitPrice() {
        return fruitPrice;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.fruit_price")
    public void setFruitPrice(Integer fruitPrice) {
        this.fruitPrice = fruitPrice;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.stock")
    public Integer getStock() {
        return stock;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.stock")
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.image_url")
    public String getImageUrl() {
        return imageUrl;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.image_url")
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.status")
    public Short getStatus() {
        return status;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.status")
    public void setStatus(Short status) {
        this.status = status;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.create_time")
    public Long getCreateTime() {
        return createTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.218+08:00",
            comments = "Source field: tbl_child_fruit.create_time")
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.219+08:00",
            comments = "Source field: tbl_child_fruit.update_time")
    public Long getUpdateTime() {
        return updateTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.219+08:00",
            comments = "Source field: tbl_child_fruit.update_time")
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.219+08:00",
            comments = "Source field: tbl_child_fruit.create_user_id")
    public String getCreateUserId() {
        return createUserId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.219+08:00",
            comments = "Source field: tbl_child_fruit.create_user_id")
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.219+08:00",
            comments = "Source field: tbl_child_fruit.update_user_id")
    public String getUpdateUserId() {
        return updateUserId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.219+08:00", comments = "Source field: tbl_child_fruit.update_user_id")
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }
}