package com.guet.qiusuo.fruittravel.model;

import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   收货地址信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbl_deliveryinfo
 */
public class DeliveryInfo {
    /**
     * Database Column Remarks:
     *   uuid
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.253+08:00", comments="Source field: tbl_deliveryinfo.id")
    private String id;

    /**
     * Database Column Remarks:
     *   用户id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.user_id")
    private String userId;

    /**
     * Database Column Remarks:
     *   收货人姓名
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.delivery_name")
    private String deliveryName;

    /**
     * Database Column Remarks:
     *   收货人电话
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.delivery_phone")
    private String deliveryPhone;

    /**
     * Database Column Remarks:
     *   收货人地址
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.delivery_address")
    private String deliveryAddress;

    /**
     * Database Column Remarks:
     *   状态，0：不启用；1：启用
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.status")
    private Short status;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.create_time")
    private Long createTime;

    /**
     * Database Column Remarks:
     *   最后更新时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.258+08:00", comments="Source field: tbl_deliveryinfo.update_time")
    private Long updateTime;

    /**
     * Database Column Remarks:
     *   增加此条数据的用户id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.258+08:00", comments="Source field: tbl_deliveryinfo.create_user_id")
    private String createUserId;

    /**
     * Database Column Remarks:
     *   最后更新此条数据的用户id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.258+08:00", comments="Source field: tbl_deliveryinfo.update_user_id")
    private String updateUserId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.256+08:00", comments="Source field: tbl_deliveryinfo.id")
    public String getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.256+08:00", comments="Source field: tbl_deliveryinfo.id")
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.user_id")
    public String getUserId() {
        return userId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.user_id")
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.delivery_name")
    public String getDeliveryName() {
        return deliveryName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.delivery_name")
    public void setDeliveryName(String deliveryName) {
        this.deliveryName = deliveryName == null ? null : deliveryName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.delivery_phone")
    public String getDeliveryPhone() {
        return deliveryPhone;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.delivery_phone")
    public void setDeliveryPhone(String deliveryPhone) {
        this.deliveryPhone = deliveryPhone == null ? null : deliveryPhone.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.delivery_address")
    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.delivery_address")
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress == null ? null : deliveryAddress.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.status")
    public Short getStatus() {
        return status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.status")
    public void setStatus(Short status) {
        this.status = status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.257+08:00", comments="Source field: tbl_deliveryinfo.create_time")
    public Long getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.258+08:00", comments="Source field: tbl_deliveryinfo.create_time")
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.258+08:00", comments="Source field: tbl_deliveryinfo.update_time")
    public Long getUpdateTime() {
        return updateTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.258+08:00", comments="Source field: tbl_deliveryinfo.update_time")
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.258+08:00", comments="Source field: tbl_deliveryinfo.create_user_id")
    public String getCreateUserId() {
        return createUserId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.258+08:00", comments="Source field: tbl_deliveryinfo.create_user_id")
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.258+08:00", comments="Source field: tbl_deliveryinfo.update_user_id")
    public String getUpdateUserId() {
        return updateUserId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-04-14T19:34:43.258+08:00", comments="Source field: tbl_deliveryinfo.update_user_id")
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }
}