package com.guet.qiusuo.fruittravel.model;

import javax.annotation.Generated;

/**
 * Database Table Remarks:
 * 水果景点表
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbl_user_role
 */
public class FruitScenic {
    /**
     * Database Column Remarks:
     * uuid
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.id")
    private String id;

    /**
     * Database Column Remarks:
     * 水果id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.fruit_id")
    private String fruitId;

    /**
     * Database Column Remarks:
     * 景点id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.scenic_id")
    private String scenicId;

    /**
     * Database Column Remarks:
     * 水果名称
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.fruit_name")
    private String fruitName;

    /**
     * Database Column Remarks:
     * 水果价钱(一个范围)
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.fruit_price")
    private String fruitPrice;

    /**
     * Database Column Remarks:
     * 水果描述
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.description")
    private String fruitDescription;

    /**
     * Database Column Remarks:
     * 发货地点
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.departure_point")
    private String departurePoint;

    /**
     * Database Column Remarks:
     * 快递费
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.delivery_cost")
    private Integer deliveryCost;

    /**
     * Database Column Remarks:
     * 景点名称
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.scenic_name")
    private String scenicName;

    /**
     * Database Column Remarks:
     * 地理位置
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.location")
    private String location;

    /**
     * Database Column Remarks:
     * 开放时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.opening_hours")
    private String openingHours;

    /**
     * Database Column Remarks:
     * 景区介绍
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.description")
    private String scenicDescription;

    /**
     * Database Column Remarks:
     * 景区类型, 1-文化古迹, 2-园林花园, 3-古镇古村, 4-城堡教堂
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.type")
    private Short type;

    /**
     * Database Column Remarks:
     * 状态,0:禁用 1:启用
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.status")
    private Short status;

    /**
     * Database Column Remarks:
     * 创建时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.create_time")
    private Long createTime;

    /**
     * Database Column Remarks:
     * 更新时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.update_time")
    private Long updateTime;

    /**
     * Database Column Remarks:
     * 记录创建人ID
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.create_user_id")
    private String createUserId;

    /**
     * Database Column Remarks:
     * 记录修改人ID
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.update_user_id")
    private String updateUserId;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.id")
    public String getId() {
        return id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.id")
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.fruit_id")
    public String getFruitId() {
        return fruitId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.fruit_id")
    public void setFruitId(String fruitId) {
        this.fruitId = fruitId == null ? null : fruitId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.fruit_name")
    public String getFruitName() {
        return fruitName;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.fruit_name")
    public void setFruitName(String fruitName) {
        this.fruitName = fruitName == null ? null : fruitName.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.fruit_price")
    public String getFruitPrice() {
        return fruitPrice;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.fruit_price")
    public void setFruitPrice(String fruitPrice) {
        this.fruitPrice = fruitPrice == null ? null : fruitPrice.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.fruitDescription")
    public String getFruitDescription() {
        return fruitDescription;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.fruitDescription")
    public void setfruitDescription(String fruitDescription) {
        this.fruitDescription = fruitDescription == null ? null : fruitDescription.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.departure_point")
    public String getDeparturePoint() {
        return departurePoint;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.departure_point")
    public void setDeparturePoint(String departurePoint) {
        this.departurePoint = departurePoint == null ? null : departurePoint.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.delivery_cost")
    public Integer getDeliveryCost() {
        return deliveryCost;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.delivery_cost")
    public void setDeliveryCost(Integer deliveryCost) {
        this.deliveryCost = deliveryCost;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.scenic_name")
    public String getScenicName() {
        return scenicName;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.scenic_name")
    public void setScenicName(String scenicName) {
        this.scenicName = scenicName == null ? null : scenicName.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.location")
    public String getLocation() {
        return location;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.location")
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.opening_hours")
    public String getOpeningHours() {
        return openingHours;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.opening_hours")
    public void setOpeningHours(String openingHours) {
        this.openingHours = openingHours == null ? null : openingHours.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.description")
    public String getscenicDescription() {
        return scenicDescription;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.description")
    public void setscenicDescription(String scenicDescription) {
        this.scenicDescription = scenicDescription == null ? null : scenicDescription.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.type")
    public Short getType() {
        return type;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.type")
    public void setType(Short type) {
        this.type = type;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.scenic_id")
    public String getScenicId() {
        return scenicId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.scenic_id")
    public void setScenicId(String scenicId) {
        this.scenicId = scenicId == null ? null : scenicId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.status")
    public Short getStatus() {
        return status;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.status")
    public void setStatus(Short status) {
        this.status = status;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.create_time")
    public Long getCreateTime() {
        return createTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.create_time")
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.update_time")
    public Long getUpdateTime() {
        return updateTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.update_time")
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.create_user_id")
    public String getCreateUserId() {
        return createUserId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.create_user_id")
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.update_user_id")
    public String getUpdateUserId() {
        return updateUserId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-02-25T11:39:23.859+08:00",
            comments = "Source field: tbl_fruit_scenic.update_user_id")
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }
}
