package com.guet.qiusuo.fruittravel.model;

import javax.annotation.Generated;

/**
 * Database Table Remarks:
 * 门票预订表
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbl_reservation
 */
public class Reservation {
    /**
     * Database Column Remarks:
     * uuid
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.254+08:00",
            comments = "Source field: tbl_reservation.id")
    private String id;

    /**
     * Database Column Remarks:
     * 用户id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.254+08:00",
            comments = "Source field: tbl_reservation.user_id")
    private String userId;

    /**
     * Database Column Remarks:
     * 门票id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.254+08:00",
            comments = "Source field: tbl_reservation.ticket_id")
    private String ticketId;

    /**
     * Database Column Remarks:
     * 门票预订的时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.255+08:00",
            comments = "Source field: tbl_reservation.reserve_time")
    private Long reserveTime;

    /**
     * Database Column Remarks:
     * 购买数量
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.255+08:00",
            comments = "Source field: tbl_reservation.quantity")
    private Integer quantity;

    /**
     * Database Column Remarks:
     * 状态, 0: 无效 1: 有效
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.255+08:00",
            comments = "Source field: tbl_reservation.status")
    private Short status;

    /**
     * Database Column Remarks:
     * 创建时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.create_time")
    private Long createTime;

    /**
     * Database Column Remarks:
     * 最后更新时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.update_time")
    private Long updateTime;

    /**
     * Database Column Remarks:
     * 增加此条数据的用户id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.create_user_id")
    private String createUserId;

    /**
     * Database Column Remarks:
     * 最后更新此条数据的用户id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.update_user_id")
    private String updateUserId;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.254+08:00",
            comments = "Source field: tbl_reservation.id")
    public String getId() {
        return id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.254+08:00",
            comments = "Source field: tbl_reservation.id")
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.254+08:00",
            comments = "Source field: tbl_reservation.user_id")
    public String getUserId() {
        return userId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.254+08:00",
            comments = "Source field: tbl_reservation.user_id")
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.254+08:00",
            comments = "Source field: tbl_reservation.ticket_id")
    public String getTicketId() {
        return ticketId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.254+08:00",
            comments = "Source field: tbl_reservation.ticket_id")
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId == null ? null : ticketId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.255+08:00",
            comments = "Source field: tbl_reservation.reserve_time")
    public Long getReserveTime() {
        return reserveTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.255+08:00",
            comments = "Source field: tbl_reservation.reserve_time")
    public void setReserveTime(Long reserveTime) {
        this.reserveTime = reserveTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.255+08:00",
            comments = "Source field: tbl_reservation.quantity")
    public Integer getQuantity() {
        return quantity;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.255+08:00",
            comments = "Source field: tbl_reservation.quantity")
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.255+08:00",
            comments = "Source field: tbl_reservation.status")
    public Short getStatus() {
        return status;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.255+08:00",
            comments = "Source field: tbl_reservation.status")
    public void setStatus(Short status) {
        this.status = status;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.create_time")
    public Long getCreateTime() {
        return createTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.create_time")
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.update_time")
    public Long getUpdateTime() {
        return updateTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.update_time")
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.create_user_id")
    public String getCreateUserId() {
        return createUserId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.create_user_id")
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.update_user_id")
    public String getUpdateUserId() {
        return updateUserId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.256+08:00",
            comments = "Source field: tbl_reservation.update_user_id")
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }
}