package com.guet.qiusuo.fruittravel.model;

import javax.annotation.Generated;

/**
 * Database Table Remarks:
 * 景点门票表
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbl_ticket
 */
public class Ticket {
    /**
     * Database Column Remarks:
     * uuid
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.281+08:00",
            comments = "Source field: tbl_ticket.id")
    private String id;

    /**
     * Database Column Remarks:
     * 景点id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.scenic_id")
    private String scenicId;

    /**
     * Database Column Remarks:
     * 门票类型, 1--成人票, 2--儿童票, 3--老人票
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.type")
    private Short type;

    /**
     * Database Column Remarks:
     * 门票价格
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.price")
    private Integer price;

    /**
     * Database Column Remarks:
     * 门票描述
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.description")
    private String description;

    /**
     * Database Column Remarks:
     * 状态, 0: 无效 1: 有效
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.status")
    private Short status;

    /**
     * Database Column Remarks:
     * 创建时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.create_time")
    private Long createTime;

    /**
     * Database Column Remarks:
     * 最后更新时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.update_time")
    private Long updateTime;

    /**
     * Database Column Remarks:
     * 增加此条数据的用户id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.create_user_id")
    private String createUserId;

    /**
     * Database Column Remarks:
     * 最后更新此条数据的用户id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.283+08:00",
            comments = "Source field: tbl_ticket.update_user_id")
    private String updateUserId;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.281+08:00",
            comments = "Source field: tbl_ticket.id")
    public String getId() {
        return id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.id")
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.scenic_id")
    public String getScenicId() {
        return scenicId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.scenic_id")
    public void setScenicId(String scenicId) {
        this.scenicId = scenicId == null ? null : scenicId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.type")
    public Short getType() {
        return type;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.type")
    public void setType(Short type) {
        this.type = type;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.price")
    public Integer getPrice() {
        return price;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.price")
    public void setPrice(Integer price) {
        this.price = price;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.description")
    public String getDescription() {
        return description;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.description")
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.status")
    public Short getStatus() {
        return status;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.status")
    public void setStatus(Short status) {
        this.status = status;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.create_time")
    public Long getCreateTime() {
        return createTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.create_time")
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.update_time")
    public Long getUpdateTime() {
        return updateTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.282+08:00",
            comments = "Source field: tbl_ticket.update_time")
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.283+08:00",
            comments = "Source field: tbl_ticket.create_user_id")
    public String getCreateUserId() {
        return createUserId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.283+08:00",
            comments = "Source field: tbl_ticket.create_user_id")
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.283+08:00",
            comments = "Source field: tbl_ticket.update_user_id")
    public String getUpdateUserId() {
        return updateUserId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-26T02:15:00.283+08:00",
            comments = "Source field: tbl_ticket.update_user_id")
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }
}