package com.guet.qiusuo.fruittravel.model;

import javax.annotation.Generated;

/**
 * Database Table Remarks:
 * 角色权限表
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbl_user_role
 */
public class UserRole {
    /**
     * Database Column Remarks:
     * uuid
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.859+08:00",
            comments = "Source field: tbl_user_role.id")
    private String id;

    /**
     * Database Column Remarks:
     * 角色id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.role_id")
    private String roleId;

    /**
     * Database Column Remarks:
     * 用户id
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.user_id")
    private String userId;

    /**
     * Database Column Remarks:
     * 状态,0:禁用 1:启用
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.status")
    private Short status;

    /**
     * Database Column Remarks:
     * 创建时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.create_time")
    private Long createTime;

    /**
     * Database Column Remarks:
     * 更新时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.update_time")
    private Long updateTime;

    /**
     * Database Column Remarks:
     * 记录创建人ID
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.create_user_id")
    private String createUserId;

    /**
     * Database Column Remarks:
     * 记录修改人ID
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.update_user_id")
    private String updateUserId;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.861+08:00",
            comments = "Source field: tbl_user_role.id")
    public String getId() {
        return id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.id")
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.role_id")
    public String getRoleId() {
        return roleId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.role_id")
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.user_id")
    public String getUserId() {
        return userId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.user_id")
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.status")
    public Short getStatus() {
        return status;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.status")
    public void setStatus(Short status) {
        this.status = status;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.create_time")
    public Long getCreateTime() {
        return createTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.create_time")
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.update_time")
    public Long getUpdateTime() {
        return updateTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.update_time")
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.create_user_id")
    public String getCreateUserId() {
        return createUserId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.862+08:00",
            comments = "Source field: tbl_user_role.create_user_id")
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.863+08:00",
            comments = "Source field: tbl_user_role.update_user_id")
    public String getUpdateUserId() {
        return updateUserId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2022-01-30T15:19:23.863+08:00",
            comments = "Source field: tbl_user_role.update_user_id")
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }
}